### ISSUE TITLE
Error when DHCP has no Static Mappings

### ISSUE THREAD

**Issue by cmacnichol** [EasyG0ing1/Migration#5]
Windows Binary 2.1.4

If you have a Subnet with DHCP Enabled but no Static mapping, the tool will error out on the following entry in the config file.

`<staticmap/>`

This will result in the static mapping error with these details.

       Mac:         NONE
       CID:         NONE
       Hostname:    NONE
       Description: NONE

Removing the line from the file corrects the issue and allows the tool to process the source config file.

**Comment by EasyG0ing1** [comment]
@cmacnichol I think you intended on providing the line in the config file that caused the error, but didn't paste it into your post.

**Comment by cmacnichol** [comment]
> @cmacnichol I think you intended on providing the line in the config file that caused the error, but didn't paste it into your post.

Looks like Github was trying to be helpful and formatted it away.  Putting it in code brackets fixed it.

**Comment by EasyG0ing1** [comment]
@cmacnichol 

Nothing better than when they try to help ;-)

Try this with your config file and tell me what happens.

[Windows-Migrate.zip](https://github.com/EasyG0ing1/Migration/files/15206635/Windows-Migrate.zip)

**Comment by EasyG0ing1** [comment]
Fixed with [Version 2.2.0](https://github.com/EasyG0ing1/Migration/releases/tag/2.2.0)
